//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traveler.StringTest", typeof(StringTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015-01-01,00:00:00,16.0,14.0,84.0,WSW,0.0,0.0,27.1,0.0
        ///2015-01-01,01:00:00,15.0,11.0,82.0,WSW,0.0,2.0,27.1,0.0
        ///2015-01-01,02:00:00,14.8,14.0,85.0,ESE,0.0,1.0,27.1,0.0
        ///2015-01-01,03:00:00,19.2,16.0,84.0,SW,3.3,6.0,27.11,0.0
        ///2015-01-01,04:00:00,23.5,18.0,78.0,WSW,8.4,11.0,27.11,0.0
        ///2015-01-01,05:00:00,25.5,21.0,79.0,WSW,6.1,12.0,27.11,0.0
        ///2015-01-01,06:00:00,25.5,21.0,79.0,WNW,5.1,6.0,27.14,0.0
        ///2015-01-01,07:00:00,25.1,21.0,81.0,NW,6.8,9.0,27.14,0.0
        ///2015-01-01,08:00:00,24.9,23.0,83.0,NW,3.7,5.0,27.15 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dec1 {
            get {
                return ResourceManager.GetString("dec1", resourceCulture);
            }
        }
    }
}
