// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "MA0007:Add a comma after the last value", Justification = "<Pending>", Scope = "member", Target = "~F:DndApp.Annotations.ImplicitUseTargetFlags.WithMembers")]
[assembly: SuppressMessage("Style", "MA0007:Add a comma after the last value", Justification = "<Pending>", Scope = "member", Target = "~F:DndApp.Annotations.InjectedLanguage.XML")]
[assembly: SuppressMessage("Style", "MA0007:Add a comma after the last value", Justification = "<Pending>", Scope = "member", Target = "~F:DndApp.Annotations.CollectionAccessType.UpdatedContent")]
[assembly: SuppressMessage("Style", "MA0003:Add parameter name to improve readability", Justification = "<Pending>", Scope = "member", Target = "~M:DndApp.Annotations.ContractAnnotationAttribute.#ctor(System.String)")]
[assembly: SuppressMessage("Style", "MA0003:Add parameter name to improve readability", Justification = "<Pending>", Scope = "member", Target = "~M:DndApp.Annotations.LocalizationRequiredAttribute.#ctor")]
[assembly: SuppressMessage("Design", "MA0062:Non-flags enums should not be marked with \"FlagsAttribute\"", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CollectionAccessType")]
[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Justification = "<Pending>", Scope = "namespace", Target = "~N:DndApp.Annotations")]
[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ImplicitUseTargetFlags")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspAttributeRoutingAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspChildControlTypeAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspDataFieldAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspDataFieldsAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspDefaultRouteValuesAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMethodPropertyAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMinimalApiDeclarationAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMinimalApiHandlerAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcActionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcActionSelectorAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcAreaAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcAreaMasterLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcAreaPartialViewLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcAreaViewLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcControllerAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcDisplayTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcEditorTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcMasterAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcMasterLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcModelTypeAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcPartialViewAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcPartialViewLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcSuppressViewErrorAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcViewAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcViewComponentAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcViewComponentViewAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspMvcViewLocationFormatAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspRequiredAttributeAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspRouteConventionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspRouteOrderAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspRouteValuesConstraintsAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspRouteVerbsAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AspTypePropertyAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AssertionConditionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AssertionConditionType")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.AssertionMethodAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.BaseTypeRequiredAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CanBeNullAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CannotApplyEqualityOperatorAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CodeTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CollectionAccessAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.CollectionAccessType")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ContractAnnotationAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.HtmlAttributeValueAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.HtmlElementAttributesAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ImplicitUseKindFlags")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ImplicitUseTargetFlags")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.InjectedLanguage")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.InstantHandleAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.InvokerParameterNameAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ItemCanBeNullAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ItemNotNullAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.LanguageInjectionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.LinqTunnelAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.LocalizationRequiredAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.MacroAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.MeansImplicitUseAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.MustUseReturnValueAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.NoEnumerationAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.NonNegativeValueAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.NoReorderAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.NotifyPropertyChangedInvocatorAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.NotNullAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.PathReferenceAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ProvidesContextAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.PublicAPIAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.PureAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorDirectiveAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorHelperCommonAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorImportNamespaceAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorInjectionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorLayoutAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorPageBaseTypeAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorSectionAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorWriteLiteralMethodAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorWriteMethodAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RazorWriteMethodParameterAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RegexPatternAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RequireStaticDelegateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RouteParameterConstraintAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.RouteTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.SourceTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.StringFormatMethodAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.StructuredMessageTemplateAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.TerminatesProgramAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.UriStringAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.UsedImplicitlyAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ValueProviderAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.ValueRangeAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.XamlItemBindingOfItemsControlAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.XamlItemsControlAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.XamlItemStyleOfItemsControlAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.XamlOneWayBindingModeByDefaultAttribute")]
[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Justification = "<Pending>", Scope = "type", Target = "~T:DndApp.Annotations.XamlTwoWayBindingModeByDefaultAttribute")]
